runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: yes

runtime_config:
  python_version: 3

env_variables:
    PEEWEE_DATABASE_URI: >-
      mysql://backend:FGXq1eNDJCrOoEKUjSUq2@/operations?unix_socket=/cloudsql/eps-scams:us-east1:eps-scams-01

beta_settings:
    cloud_sql_instances: eps-scams:us-east1:eps-scams-01

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10